### ISSUE TITLE
Python error on Splunk 9.3.1

### ISSUE THREAD

**Issue by afxmac** [LukeMurphey/splunk-website-monitoring#60] opened 2024-10-22 07:24 UTC
Hi, since the update to Splunk 9.3.1 I get the following error from the website monitoring app (2.9.6)

`ERROR ScriptRunner [1147557 TcpChannelThread] - stderr from '/opt/splunk/bin/python3.9 /opt/splunk/bin/runScript.py setup': /opt/splunk/etc/apps/website_monitoring/bin/modular_input.zip/modular_input/contrib/ipaddress.py:1106: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?` 

Any chance you could look at this?
thx
afx

**Comment by LukeMurphey** [comment] 2024-10-27 01:24
This appears to be an issue in one of the libraries being used.

- https://github.com/phihag/ipaddress/pull/48
- https://github.com/pypa/pip/issues/7214
- https://github.com/pypa/pip/issues/7615

I'll look into see if I can update the dependency.

**Comment by LukeMurphey** [comment] 2024-10-28 17:35
I have a fix for this. I have deployed the changes on my Splunk instance and everything seems to be working. That said, I wasn't able to reproduce the issue so I'm not 100% certain that I have fixed it.

However, I was able to determine that I was using an old library that was known to have this issue. I'm now using the version of the library bundled with Python 3 which ought to be more stable.

**Comment by LukeMurphey** [comment] 2024-10-28 17:43
A fix for this is available in version 2.9.7. See https://splunkbase.splunk.com/app/1493

**Closed** 2024-10-28 17:43 UTC
