### ISSUE TITLE
App stops running after connection error

### ISSUE THREAD

**Issue by G4m3M4ni4c** [LukeMurphey/splunk-website-monitoring#9] opened 2016-09-08 14:18 UTC
The app stops running after the following error. (Using Website Monitoring version: 1.6.1)

```
ERROR Execution failed
Traceback (most recent call last):
  File "F:\Program Files\Splunk\etc\apps\website_monitoring\bin\modular_input.py", line 1277, in execute
    self.do_run(in_stream, log_exception_and_continue=True)
  File "F:\Program Files\Splunk\etc\apps\website_monitoring\bin\modular_input.py", line 1177, in do_run
    input_config)
  File "F:\Program Files\Splunk\etc\apps\website_monitoring\bin\web_ping.py", line 485, in run
    proxy_type, proxy_server, proxy_port, proxy_user, proxy_password = self.get_proxy_config(input_config.session_key, conf_stanza)
  File "F:\Program Files\Splunk\etc\apps\website_monitoring\bin\web_ping.py", line 453, in get_proxy_config
    website_monitoring_config = WebsiteMonitoringConfig.get( WebsiteMonitoringConfig.build_id( stanza, "website_monitoring", "nobody"), sessionKey=session_key )
  File "F:\Program Files\Splunk\Python-2.7\Lib\site-packages\splunk\models\base.py", line 548, in get
    return SplunkRESTManager(cls, sessionKey=sessionKey).get(id)
  File "F:\Program Files\Splunk\Python-2.7\Lib\site-packages\splunk\models\base.py", line 528, in get
    entity = self._get_entity(id, host_path=host_path)
  File "F:\Program Files\Splunk\Python-2.7\Lib\site-packages\splunk\models\base.py", line 444, in _get_entity
    return self._fix_entity(splunk.entity.getEntity(self.model.resource, None, sessionKey=self.sessionKey, uri=id))
  File "F:\Program Files\Splunk\Python-2.7\Lib\site-packages\splunk\entity.py", line 249, in getEntity
    serverResponse, serverContent = rest.simpleRequest(uri, getargs=kwargs, sessionKey=sessionKey, raiseAllErrors=True)
  File "F:\Program Files\Splunk\Python-2.7\Lib\site-packages\splunk\rest\__init__.py", line 480, in simpleRequest
    raise splunk.SplunkdConnectionException, 'Error connecting to %s: %s' % (path, str(e))
SplunkdConnectionException: Splunkd daemon is not responding: ("Error connecting to /servicesNS/nobody/website_monitoring/admin/website_monitoring/proxy_NTLMaps: ('The read operation timed out',)",)
```

**Comment by G4m3M4ni4c** [comment] 2016-09-21 10:30
Is there anything you can do to stop the error from crashing your app? It is becoming a big problem where I work.

**Comment by LukeMurphey** [comment] 2016-09-21 16:11
The SplunkdConnectionException usually only happens when Splunk is being shut down. This happens because Splunk shuts down splunkd before it shuts down the modular input processes. Could you verify that these happen when Splunk is being shut down and/or look to see if other exceptions exist? The searches defined in the troubleshooting section here might reveal more information on the root cause: http://lukemurphey.net/projects/splunk-website-monitoring/wiki/Troubleshooting

**Comment by G4m3M4ni4c** [comment] 2016-09-22 09:55
I have recently found a new error which may help find the root cause.
`09-22-2016 00:09:43.357 +0100 WARN  HttpListener - Socket error from 127.0.0.1 while accessing /servicesNS/nobody/website_monitoring/admin/website_monitoring/proxy_Squid: Winsock error 10053`

**Comment by LukeMurphey** [comment] 2016-09-22 15:02
Perfect, thats looks like one I don't currently handle.

**Comment by LukeMurphey** [comment] 2016-09-22 15:10
Actually, I'm not entirely sure what is happening there. I thought this was an exception logged from within Website Monitoring itself but it doesn't appear to be. Rather it appears that Splunk is struggling to connect to itself on 127.0.0.1. In this case, the SplunkdConnectionException exceptions are _not_ the normal ones that happen when an input shuts down.

I have never seen this before. Not sure why the host would have anything less than a prefect connection to itself.

**Comment by G4m3M4ni4c** [comment] 2016-09-22 15:23
This log came from splunkd.log

**Comment by G4m3M4ni4c** [comment] 2016-09-22 15:23
The proxy is running on the same box as splunk

**Comment by G4m3M4ni4c** [comment] 2016-09-22 15:24
the operating system is windows 2008

**Comment by LukeMurphey** [comment] 2016-09-22 15:24
Fix will be released in version 1.6.2 (change is already committed). See http://lukemurphey.net/issues/1498.

**Comment by G4m3M4ni4c** [comment] 2016-09-22 15:25
cool, so did you find the problem?

**Comment by LukeMurphey** [comment] 2016-09-22 15:38
Kind of. I think something strange is happening on that Splunk host. For some reason, Splunk's internal communication is failing at times. I changed the input to be try to ignore these errors and try again. Hopefully, the error is infrequent enough that the input will just try again and it will work the next time.

To be clear, I don't _believe_ the proxy is the problem. Unless the proxy is being used when Splunk talks to itself over loopback, but that would be bizarre. I really can't figure out what the root cause of the Splunkd connection issues since that is unlikely to be related to the Website Monitoring app. However, version 1.6.2 should work on a host has an occasional connection issue when attempting to contact Splunkd.

**Comment by LukeMurphey** [comment] 2016-09-23 20:41
1.6.2 has been released with a workaround for this.

**Closed by LukeMurphey** 2016-09-23 20:41 UTC
